### ISSUE TITLE
Release to Sonatype?

### ISSUE THREAD

**Issue by ticofab** [workingDog/kmlToGeojson#1]
Is this library available on some public repository à la Maven? Thanks!

**Comment by workingDog** [comment]
Hi Fabio,

it is not available on a public repo yet, because I don't know how to do it.
I will investigate how to put it on Maven.

**Comment by workingDog** [comment]
I've released the project on The Central Repository. 
To include it in your code, just add this to your build.sbt:
       libraryDependencies += "com.github.workingDog" %% "kmltogeojson" % "1.0"
Note the change of name, see also the updated doc

**Comment by ticofab** [comment]
thanks!
